# Day 7: Linear Algebra - Matrices and Matrix Operations


In [1]:
import numpy as np

In [5]:
x1 = np.array([[1, 2, 3], [4, 5, 6]])

y1 = np.array([[7, 8, 9], [10, 11, 12]])

z1 = np.array([[1, 3], [5, 7], [9, 11]])


In [6]:
x1, y1, z1

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 1,  3],
        [ 5,  7],
        [ 9, 11]]))

In [7]:
x1.shape, y1.shape, z1.shape

((2, 3), (2, 3), (3, 2))

In [8]:
x1 + y1

array([[ 8, 10, 12],
       [14, 16, 18]])

In [9]:
x1 + z1

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [10]:
5 * x1

array([[ 5, 10, 15],
       [20, 25, 30]])

In [11]:
x1 @ z1

array([[ 38,  50],
       [ 83, 113]])

In [12]:
x1 @ y1

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [14]:
x2 = np.random.randint(0, 10, size=(4, 4))
y2 = np.random.randint(0, 10, size=(4, 4))
x2, y2


(array([[0, 0, 0, 8],
        [0, 4, 9, 7],
        [1, 4, 7, 9],
        [6, 8, 9, 9]]),
 array([[7, 0, 1, 7],
        [4, 8, 7, 9],
        [5, 0, 0, 9],
        [9, 5, 8, 1]]))

In [15]:
x2 @ y2

array([[ 72,  40,  64,   8],
       [124,  67,  84, 124],
       [139,  77, 101, 115],
       [200, 109, 134, 204]])

In [16]:
y2 @ x2

array([[ 43,  60,  70, 128],
       [ 61, 132, 202, 232],
       [ 54,  72,  81, 121],
       [ 14,  60, 110, 188]])

In [17]:
X = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
X_T = X.transpose()


In [18]:
X, X_T

(array([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]),
 array([[ 1,  7, 13],
        [ 3,  9, 15],
        [ 5, 11, 17]]))

In [25]:
X = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
X_inv = np.linalg.inv(X)

print(X, "\n")
print(X_inv)


[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]] 

[[-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
 [ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]
 [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]]


In [26]:
X @ X_inv  # eh

array([[ 1.03125, -0.5    ,  0.1875 ],
       [ 0.46875,  0.     ,  0.3125 ],
       [-0.09375,  2.     ,  0.9375 ]])

In [28]:
mat_X = np.array([[5, 3, 1], [9, 6, 3], [13, 12, 11]])
mat_Y = np.array([[4, 7, 8], [22, 45, 76], [32, 24, 54]])
mat_XY = mat_X @ mat_Y

mat_XY_T = mat_XY.T
mat_XY_T2 = np.transpose(mat_XY)

mat_XY_inv = np.linalg.inv(mat_XY_T)

print(mat_XY, "\n")
print(mat_XY_T, "\n")
print(mat_XY_T2, "\n")
print(mat_XY_inv)


[[ 118  194  322]
 [ 264  405  690]
 [ 668  895 1610]] 

[[ 118  264  668]
 [ 194  405  895]
 [ 322  690 1610]] 

[[ 118  264  668]
 [ 194  405  895]
 [ 322  690 1610]] 

[[-2.81926058e+13 -2.93203101e+13  2.79964834e+13]
 [ 1.97348241e+13  2.05242171e+13 -1.95975384e+13]
 [-2.81926058e+12 -2.93203101e+12  2.79964834e+12]]
